"use client";
type V={x:number;y:number;z:number};
export type SceneObject={key:string;id?:number;kind:"vehicle"|"walker"|"building"|"road"|"prop";name:string;label:string;location:V;extent:V;hero?:boolean;origin?:"native"|"user";user_created?:boolean};
export type SceneState={map:string;bounds:{min_x:number;max_x:number;min_y:number;max_y:number};road_points:V[];objects:SceneObject[];static_targets:SceneObject[];spectator:{location:V;rotation:{yaw:number;pitch:number}};hero_id:number|null;hero_lock:boolean};
const colors={vehicle:"#00aaff",walker:"#ffc800",building:"#be50ff",road:"#ff4646",prop:"#3cdc78"};
export default function BevMap({state,selected,onPick,onDropBlueprint}:{state:SceneState|null;selected:string;onPick:(object:SceneObject)=>void;onDropBlueprint?:(blueprint:string,x:number,y:number)=>void}){
 if(!state)return <div className="bev"><span>Waiting for CARLA map…</span></div>;
 const b=state.bounds,w=Math.max(1,b.max_x-b.min_x),h=Math.max(1,b.max_y-b.min_y),xy=(v:V)=>({x:(v.x-b.min_x)/w*1000,y:(b.max_y-v.y)/h*700});
 const objects=[...state.static_targets,...state.objects],spectator=xy(state.spectator.location);
 function point(e:React.MouseEvent<SVGSVGElement>|React.DragEvent<SVGSVGElement>){const r=e.currentTarget.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*1000,py=(e.clientY-r.top)/r.height*700;return{x:b.min_x+px/1000*w,y:b.max_y-py/700*h}}
 return <div className={`bev ${onDropBlueprint?"drop-enabled":""}`}><div className="previewbar"><b>LIVE BEV · {state.map.split("/").pop()}</b><span>{onDropBlueprint?"Drag a blueprint here to create it":"Click an object or empty map position"}</span></div><svg viewBox="0 0 1000 700" onDragOver={e=>{if(onDropBlueprint)e.preventDefault()}} onDrop={e=>{if(!onDropBlueprint)return;e.preventDefault();const id=e.dataTransfer.getData("application/x-carla-blueprint");if(id){const p=point(e);onDropBlueprint(id,p.x,p.y)}}} onClick={e=>{const p=point(e);fetch("http://127.0.0.1:8765/focus/bev",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)})}}>{state.road_points.map((p,i)=>{const q=xy(p);return <circle key={i} cx={q.x} cy={q.y} r="2.2" className="bev-road"/>})}{objects.map(o=>{const q=xy(o.location);return <g key={o.key} className={selected===o.key?"selected":""} onClick={e=>{e.stopPropagation();onPick(o)}}><circle cx={q.x} cy={q.y} r={o.kind==="building"?12:o.kind==="road"?9:7} fill={colors[o.kind]}/>{o.hero&&<circle cx={q.x} cy={q.y} r="13" className="hero-ring"/>}</g>})}<g transform={`translate(${spectator.x} ${spectator.y}) rotate(${state.spectator.rotation.yaw})`}><path d="M 16 0 L -10 -9 L -6 0 L -10 9 Z" className="bev-camera"/></g></svg><div className="bev-legend">{Object.entries(colors).map(([k,v])=><span key={k}><i style={{background:v}}/>{k}</span>)}</div></div>
}
