"use client";
import {useEffect,useMemo,useState} from "react";

const bridge="http://127.0.0.1:8765";
type Route={name:string;path:string;relative:string;count:number};
type Status={algorithms:{id:string;name:string;framework:string;checkpoint:string;sensors:string;enabled:boolean}[];job:{state:string;kind:string|null;started_at:number|null;returncode:number|null};routes:Route[];log:string;results:unknown};

export default function EndToEndPage(){
 const [data,setData]=useState<Status|null>(null),[route,setRoute]=useState(""),[message,setMessage]=useState("Connecting to evaluation service…"),[filter,setFilter]=useState("");
 const refresh=()=>fetch(`${bridge}/e2e/status`).then(r=>r.json()).then(v=>{setData(v);setMessage(v.job.state==="running"?`${v.job.kind} is running`:"Evaluation service ready");if(!route&&v.routes.length)setRoute(v.routes[0].path)}).catch(e=>setMessage(String(e)));
 useEffect(()=>{refresh();const timer=setInterval(refresh,1500);return()=>clearInterval(timer)},[]);
 const routes=useMemo(()=>data?.routes.filter(v=>v.relative.toLowerCase().includes(filter.toLowerCase()))??[],[data,filter]);
 async function action(kind:string){setMessage(`Starting ${kind}…`);const r=await fetch(`${bridge}/e2e/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:kind,algorithm:"uniad",route})}),v=await r.json();setMessage(r.ok?`${kind} started`:v.error);refresh()}
 async function stop(){await fetch(`${bridge}/e2e/stop`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});setMessage("Stopping evaluation…");refresh()}
 const running=data?.job.state==="running"||data?.job.state==="stopping",algorithm=data?.algorithms[0];
 return <section className="e2e-page"><div className="e2e-sidebar"><span className="eyebrow">ALGORITHM CATALOG</span><h2>End-to-End Testing</h2><p>Run driving algorithms as targets while the safety agent searches for critical failures.</p><div className="algorithm-card selected"><div className="algorithm-mark">U</div><div><strong>{algorithm?.name??"UniAD-Tiny"}</strong><small>{algorithm?.framework??"Bench2Drive"} · {algorithm?.sensors??"6 cameras"}</small></div><span>READY</span></div><div className="coming-soon"><b>1 algorithm installed</b><small>Additional targets will appear here without changing the evaluation workflow.</small></div></div><div className="e2e-main"><div className="e2e-summary"><div><span>MODEL</span><strong>{algorithm?.name??"UniAD-Tiny"}</strong><small>{algorithm?.checkpoint??"uniad_tiny_b2d.pth"}</small></div><div><span>RUNTIME</span><strong>CUDA 12.8</strong><small>RTX 5070 Ti · Python 3.10</small></div><div><span>JOB STATE</span><strong className={`job-${data?.job.state??"idle"}`}>{data?.job.state??"loading"}</strong><small>{data?.job.kind??"No active task"}</small></div></div><div className="e2e-control"><div><label>Bench2Drive route</label><input placeholder="Filter local routes" value={filter} onChange={e=>setFilter(e.target.value)}/><select value={route} onChange={e=>setRoute(e.target.value)}>{routes.map(v=><option key={v.path} value={v.path}>{v.relative}</option>)}</select><small>{data?.routes.length??0} local route files discovered</small></div><div className="e2e-actions"><button disabled={running} onClick={()=>action("doctor")}>Check environment</button><button disabled={running} onClick={()=>action("model-smoke")}>Load model on GPU</button><button className="primary" disabled={running||!route} onClick={()=>action("run")}>Start closed-loop test</button><button className="danger" disabled={!running} onClick={stop}>Stop</button></div></div><div className="e2e-console"><div className="stagebar"><span>LIVE EVALUATION LOG</span><em>{message}</em></div><pre>{data?.log||"Choose an environment check, GPU model load, or closed-loop route test."}</pre></div></div></section>
}
