"use client";
import {useEffect,useMemo,useState} from "react";

const bridge="http://127.0.0.1:8765";
type Category={id:string;group:string;coarse:string;count:number;editable:string};
export type CatalogItem={key:string;id:number|string;source:"actor"|"environment";category:string;group:string;kind:string;name:string;label:string;origin?:"user"|"evaluation";location:{x:number;y:number;z:number};extent:{x:number;y:number;z:number};rotation?:{pitch:number;yaw:number;roll:number}};
async function request(path:string,method="GET",data?:unknown){const r=await fetch(`${bridge}/${path}`,{method,headers:data?{"Content-Type":"application/json"}:undefined,body:data?JSON.stringify(data):undefined}),v=await r.json();if(!r.ok)throw new Error(v.error);return v}

export default function ObjectManager({onChanged,onTextureTarget}:{onChanged:()=>void;onTextureTarget:(item:CatalogItem)=>void}){
 const [categories,setCategories]=useState<Category[]>([]),[category,setCategory]=useState("buildings"),[items,setItems]=useState<CatalogItem[]>([]),[query,setQuery]=useState(""),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[selected,setSelected]=useState<CatalogItem|null>(null),[status,setStatus]=useState("Ready"),[hidden,setHidden]=useState<Set<string>>(new Set()),[form,setForm]=useState({x:0,y:0,z:1,yaw:0}),[revision,setRevision]=useState(0);
 useEffect(()=>{const load=()=>request("catalog/categories").then(v=>setCategories(v.categories)).catch(e=>setStatus(e.message));load();const timer=setInterval(load,2500);return()=>clearInterval(timer)},[revision]);
 useEffect(()=>{const load=()=>request(`catalog/objects?category=${encodeURIComponent(category)}&q=${encodeURIComponent(query)}&offset=${offset}&limit=50`).then(v=>{setItems(v.objects);setTotal(v.total);setCategories(current=>current.map(c=>c.id===category?{...c,count:v.total}:c));setSelected((current:CatalogItem|null)=>v.objects.find((item:CatalogItem)=>item.key===current?.key)??v.objects[0]??null);setStatus("Live scene synchronized")}).catch(e=>setStatus(e.message));const delay=setTimeout(load,180),live=setInterval(load,2000);return()=>{clearTimeout(delay);clearInterval(live)}},[category,query,offset,revision]);
 useEffect(()=>{if(selected)setForm({x:selected.location.x,y:selected.location.y,z:selected.location.z,yaw:selected.rotation?.yaw??0})},[selected]);
 const groups=useMemo(()=>Object.entries(categories.reduce<Record<string,Category[]>>((a,c)=>{(a[c.group]??=[]).push(c);return a},{})),[categories]);
 async function act(path:string,data:unknown,message:string,refreshList=false){try{await request(path,"POST",data);setStatus(message);if(refreshList)setRevision(v=>v+1);onChanged()}catch(e){setStatus(e instanceof Error?e.message:"Operation failed")}}
 async function focus(item:CatalogItem){setSelected(item);await act(item.source==="actor"?"focus/actor":"focus/environment",item.source==="actor"?{actor_id:item.id}:{object_id:item.id},`Focused ${item.name}`)}
 async function visibility(){if(!selected||selected.source!=="environment")return;const visible=hidden.has(String(selected.id));await act("objects/environment/visibility",{object_id:selected.id,visible},visible?"Object restored":"Object hidden");setHidden(prev=>{const n=new Set(prev);visible?n.delete(String(selected.id)):n.add(String(selected.id));return n})}
 async function update(){if(!selected||selected.source!=="actor")return;await act("objects/update",{actor_id:selected.id,transform:{location:{x:form.x,y:form.y,z:form.z},rotation:{yaw:form.yaw}}},"Actor transform updated",true)}
 return <section className="object-manager"><div className="manager-head"><div><span className="eyebrow">WORLD OBJECTS</span><h2>Scene Object Manager</h2></div><span>{status}</span></div><div className="manager-grid"><aside className="catalog-groups">{groups.map(([group,list])=><div key={group}><b>{group.replaceAll("_"," ")}</b>{list.map(c=><button key={c.id} className={category===c.id?"active":""} onClick={()=>{setCategory(c.id);setOffset(0);setSelected(null)}}><span>{c.id.replaceAll("_"," ")}</span><em>{c.count}</em></button>)}</div>)}</aside><div className="catalog-list"><input placeholder="Search name or ID" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}}/><select size={15} value={selected?.key??""} onChange={e=>{const item=items.find(v=>v.key===e.target.value);if(item)focus(item)}}>{items.map(item=><option key={item.key} value={item.key}>{hidden.has(String(item.id))?"[hidden] ":""}{item.origin==="user"?"[added] ":item.origin==="evaluation"?"[route] ":""}{item.label}</option>)}</select><div className="pager"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><span>{total?`${offset+1}–${Math.min(offset+50,total)} / ${total}`:"0 objects"}</span><button disabled={offset+50>=total} onClick={()=>setOffset(offset+50)}>Next</button></div></div><aside className="object-inspector"><h3>{selected?.name??"Select an object"}</h3>{selected&&<><dl><div><dt>Source</dt><dd>{selected.origin==="user"?"added by you":selected.origin==="evaluation"?"evaluation route":selected.source}</dd></div><div><dt>Category</dt><dd>{selected.category}</dd></div><div><dt>ID</dt><dd>{selected.id}</dd></div></dl><div className="transform-grid">{(["x","y","z","yaw"] as const).map(k=><label key={k}>{k.toUpperCase()}<input type="number" step="0.5" value={form[k]} onChange={e=>setForm({...form,[k]:+e.target.value})}/></label>)}</div><button onClick={()=>focus(selected)}>Focus & highlight</button><button className="primary" onClick={()=>onTextureTarget(selected)}>Edit texture</button>{selected.source==="actor"?<><button onClick={update}>Apply transform</button><button onClick={()=>act("objects/duplicate",{actor_id:selected.id},"Actor duplicated",true)}>Duplicate</button><button className="danger" onClick={()=>act("objects/delete",{actor_id:selected.id},"Actor deleted",true)}>Delete actor</button></>:<button onClick={visibility}>{hidden.has(String(selected.id))?"Restore object":"Hide object"}</button>}</>}</aside></div></section>
}
