"use client";
import {ChangeEvent,useCallback,useEffect,useMemo,useRef,useState} from "react";
import BevMap,{SceneObject,SceneState} from "./BevMap";
import AssetCameraPreview from "./AssetCameraPreview";
import BuildingSurfaceEditor from "./BuildingSurfaceEditor";
import CarPreview,{MeshData} from "./CarPreview";
import CreateObjectPage from "./CreateObjectPage";
import ObjectManager,{CatalogItem} from "./ObjectManager";
import PedestrianClothingEditor from "./PedestrianClothingEditor";
import ProjectionEditor from "./ProjectionEditor";
import RoadSurfaceEditor from "./RoadSurfaceEditor";
import ScenarioGeneratorPage from "./ScenarioGeneratorPage";
import Surface3DPreview from "./Surface3DPreview";

type Studio="vehicle"|"pedestrian"|"buildings"|"bridges"|"walls"|"fences"|"roads"|"road_lines"|"sidewalks"|"ground"|"terrain"|"vegetation"|"water"|"poles"|"guard_rails"|"traffic_signs"|"traffic_lights"|"parked_cars"|"dynamic_props"|"static_props"|"spawned_props";
type Page="edit"|"create"|"generate";
const bridge="http://127.0.0.1:8765";
const labels:Record<Studio,string>={vehicle:"Vehicles",pedestrian:"Pedestrians",buildings:"Buildings",bridges:"Bridges",walls:"Walls",fences:"Fences",roads:"Roads",road_lines:"Road Lines",sidewalks:"Sidewalks",ground:"Ground",terrain:"Terrain",vegetation:"Vegetation",water:"Water",poles:"Poles",guard_rails:"Guard Rails",traffic_signs:"Traffic Signs",traffic_lights:"Traffic Lights",parked_cars:"Parked Cars",dynamic_props:"Dynamic Props",static_props:"Static Props",spawned_props:"Spawned Props"};
const roadStudios=new Set<Studio>(["roads","road_lines","sidewalks","ground","terrain","water"]);
type VehicleMeshCatalog=Record<string,{url:string;slot:number;slotName:string;baseType:string}>;

export default function Home(){
 const output=useRef<HTMLCanvasElement>(null);
 const [page,setPage]=useState<Page>("edit"),[studio,setStudio]=useState<Studio>("vehicle"),[image,setImage]=useState<HTMLImageElement|null>(null),[base,setBase]=useState<HTMLImageElement|null>(null),[meshes,setMeshes]=useState<Record<string,MeshData>>({}),[meshCatalog,setMeshCatalog]=useState<VehicleMeshCatalog>({}),[fileName,setFileName]=useState("No image selected"),[revision,setRevision]=useState(0),[applyState,setApplyState]=useState("Bridge ready"),[applying,setApplying]=useState(false),[scene,setScene]=useState<SceneState|null>(null),[selected,setSelected]=useState(""),[refresh,setRefresh]=useState(0),[catalogTarget,setCatalogTarget]=useState<CatalogItem|null>(null);
 useEffect(()=>{const n=new Image();n.onload=()=>setBase(n);n.src="/tesla-model3-bodywork.png";Promise.all([fetch("/tesla-model3-uv0.json").then(r=>r.json()),fetch("/european-hgv-uv0.json").then(r=>r.json()),fetch("/vehicle-mesh-catalog.json").then(r=>r.json())]).then(([tesla,hgv,catalog])=>{setMeshes({"vehicle.tesla.model3":tesla,"vehicle.carlamotors.european_hgv":hgv});setMeshCatalog(catalog)})},[]);
 useEffect(()=>{let live=true;const poll=()=>fetch(`${bridge}/scene/state`).then(r=>r.json()).then(v=>{if(live)setScene(v)}).catch(()=>{});poll();const timer=setInterval(poll,700);return()=>{live=false;clearInterval(timer)}},[refresh]);
 const rendered=useCallback(()=>setRevision(v=>v+1),[]);
 const objects=useMemo(()=>{if(!scene)return[];const all=[...scene.static_targets,...scene.objects];if(studio==="vehicle")return all.filter(o=>o.kind==="vehicle");if(studio==="pedestrian")return all.filter(o=>o.kind==="walker");if(roadStudios.has(studio))return all.filter(o=>o.kind==="road");return all.filter(o=>o.kind==="building"||o.kind==="prop")},[scene,studio]);
 useEffect(()=>{if(objects.length&&!objects.some(o=>o.key===selected))setSelected(objects[0].key)},[objects,selected]);
 function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const u=URL.createObjectURL(f),n=new Image();n.onload=()=>{setImage(n);URL.revokeObjectURL(u)};n.src=u;setFileName(f.name)}
 function png(){const a=document.createElement("a");a.download=`${studio}-texture.png`;a.href=output.current?.toDataURL("image/png")??"";a.click()}
 async function post(path:string,data:unknown){const r=await fetch(`${bridge}/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),v=await r.json();if(!r.ok)throw new Error(v.error);return v}
 async function focus(o:SceneObject){const compatible=(studio==="pedestrian"&&o.kind==="walker")||(studio==="vehicle"&&o.kind==="vehicle")||(roadStudios.has(studio)&&o.kind==="road")||(!roadStudios.has(studio)&&(o.kind==="building"||o.kind==="prop"));if(compatible){setSelected(o.key);setCatalogTarget(null)}setApplyState(`Focused ${o.label}`);if(o.id)await post("focus/actor",{actor_id:o.id});else await post("focus/static",{kind:o.kind,name:o.name})}
 async function toggleHero(){try{const v=await post("camera/hero-lock",{enabled:!scene?.hero_lock});setApplyState(v.enabled?`Hero camera locked to actor ${v.hero_id}`:"Hero camera released")}catch(e){setApplyState(e instanceof Error?e.message:"Hero camera failed")}}
 async function apply(){if(!output.current)return;setApplying(true);setApplyState("Uploading texture…");try{const blob=await new Promise<Blob>((ok,no)=>output.current!.toBlob(v=>v?ok(v):no(new Error("PNG encoding failed")),"image/png"));const target=objects.find(o=>o.key===selected),actorId=catalogTarget?.source==="actor"?catalogTarget.id:target?.id;const endpoint=catalogTarget?.source==="environment"?`apply/environment?object_id=${encodeURIComponent(catalogTarget.id)}`:studio==="vehicle"?`apply?actor_id=${actorId??""}`:studio==="pedestrian"?`apply/pedestrian?actor_id=${actorId??""}`:roadStudios.has(studio)?"apply/road?scope=all":`apply/building?target=${encodeURIComponent(target?.name??"BP_House16")}`;const r=await fetch(`${bridge}/${endpoint}`,{method:"POST",headers:{"Content-Type":"image/png"},body:blob}),v=await r.json();if(!r.ok)throw new Error(v.error);setApplyState(`Applied texture to ${v.object_name??v.object_count??v.actor_id}`)}catch(e){setApplyState(e instanceof Error?e.message:"Apply failed")}finally{setApplying(false)}}
 function changeStudio(next:Studio){setStudio(next);setCatalogTarget(null);setImage(null);setFileName("No image selected");setApplyState("Bridge ready")}
 function editCatalogTexture(item:CatalogItem){const next=item.kind==="walker"?"pedestrian":item.kind==="vehicle"?"vehicle":((item.category in labels?item.category:item.kind==="road"?"roads":"buildings") as Studio);setPage("edit");setStudio(next);setCatalogTarget(item);setImage(null);setFileName("No image selected");setApplyState(`Texture target: ${item.name}`);window.scrollTo({top:0,behavior:"smooth"})}
 const target=objects.find(o=>o.key===selected),activeTarget=catalogTarget??target,vehicleBlueprint=studio==="vehicle"&&activeTarget?.kind==="vehicle"?activeTarget.name:"",mesh=meshes[vehicleBlueprint]??null,isTesla=vehicleBlueprint==="vehicle.tesla.model3",hasVehicleMesh=!!mesh,isVehicleEditor=studio==="vehicle",previewKind=studio==="pedestrian"?"pedestrian":roadStudios.has(studio)?"road":"building",title=studio==="vehicle"?`${vehicleBlueprint||"SELECTED"} BODY SURFACE`:labels[studio].toUpperCase()+" SURFACE";
 useEffect(()=>{const entry=meshCatalog[vehicleBlueprint];if(!entry||meshes[vehicleBlueprint])return;fetch(entry.url).then(r=>r.json()).then(data=>setMeshes(current=>({...current,[vehicleBlueprint]:data})))},[vehicleBlueprint,meshCatalog,meshes]);
 return <main>
  <header><div><span className="eyebrow">CARLA SAFETY AGENT</span><h1>Scene Control Studio</h1></div><nav className="page-nav"><button className={page==="edit"?"active":""} onClick={()=>setPage("edit")}>Edit World</button><button className={page==="create"?"active":""} onClick={()=>setPage("create")}>Create Objects</button><button className={page==="generate"?"active":""} onClick={()=>setPage("generate")}>Generate Scene</button></nav><div className="status"><i/>{scene?`${scene.map.split("/").pop()} · ${scene.objects.length} dynamic objects`:"Connecting to CARLA…"}</div></header>
  {page==="generate"?<ScenarioGeneratorPage/>:page==="create"?<CreateObjectPage scene={scene} onChanged={()=>setRefresh(v=>v+1)} onPick={focus}/>:<><div className="viewtabs">{(Object.keys(labels) as Studio[]).map(v=><button key={v} className={studio===v?"active":""} onClick={()=>changeStudio(v)}>{labels[v]}</button>)}</div><section className="workspace">
   <aside className="controls"><div className="section"><label htmlFor="target">Texture target</label>{catalogTarget?<div className="note"><strong>{catalogTarget.name}</strong><p>{catalogTarget.category.replaceAll("_"," ")} · selected from World Objects</p></div>:<><select id="target" value={selected} onChange={e=>{const o=objects.find(v=>v.key===e.target.value);if(o)focus(o)}}>{objects.length?objects.map(o=><option value={o.key} key={o.key}>{o.label}</option>):<option value="">No matching objects</option>}</select><button disabled={!target} onClick={()=>target&&focus(target)}>Focus & highlight</button></>}</div><div className="section"><button className={scene?.hero_lock?"primary":""} onClick={toggleHero}>{scene?.hero_lock?"Release hero camera":"Lock hero camera"}</button><small>Follow the only role_name=hero vehicle.</small></div><div className="section"><label className="upload">Upload image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><small>{fileName}</small></div><div className="note"><strong>Category highlights</strong><p>Vehicles blue · pedestrians yellow · buildings purple · roads red · props green.</p></div></aside>
   <div className="visuals"><div className="stage surface-stage"><div className="stagebar"><span>2D TEXTURE · {title}</span><span>{isVehicleEditor?"Decal · tile · cover":"Local decal, tile or cover"}</span></div>{hasVehicleMesh?<ProjectionEditor mesh={mesh} base={isTesla?base:null} image={image} output={output} onRender={rendered} useSourceUV={!isTesla} label={`${vehicleBlueprint} · ${meshCatalog[vehicleBlueprint]?.slotName??"Bodywork"}`}/>:isVehicleEditor?<BuildingSurfaceEditor image={image} output={output} onRender={rendered} label={`${vehicleBlueprint} runtime diffuse atlas`} note="This blueprint has no successfully exported web mesh; CARLA is the authoritative preview."/>:roadStudios.has(studio)?<RoadSurfaceEditor image={image} output={output} onRender={rendered}/>:studio==="pedestrian"?<PedestrianClothingEditor image={image} output={output} onRender={rendered}/>:<BuildingSurfaceEditor image={image} output={output} onRender={rendered} label={catalogTarget?.name} note={catalogTarget?"Semantic surface preview; CARLA remains authoritative until this asset mesh is exported.":undefined}/>}<canvas className="atlas-output" ref={output} width={hasVehicleMesh?2048:1024} height={hasVehicleMesh?2048:1024}/></div>{hasVehicleMesh?<CarPreview mesh={mesh} atlas={output} revision={revision} useSourceUV={!isTesla} label={`${vehicleBlueprint} · LIVE 3D BODYWORK`}/>:isVehicleEditor?<AssetCameraPreview blueprint={vehicleBlueprint} label={activeTarget?.label??"No vehicle"}/>:<Surface3DPreview atlas={output} revision={revision} kind={previewKind} label={activeTarget?.label??"No target"}/>}<BevMap state={scene} selected={selected} onPick={focus}/><ObjectManager onChanged={()=>setRefresh(v=>v+1)} onTextureTarget={editCatalogTexture}/></div>
   <aside className="export"><span className="eyebrow">LIVE OUTPUT</span><h2>Send to CARLA</h2><p>Check placement in both the 2D texture and interactive 3D preview before applying.</p><button className="primary" disabled={!image||applying||!activeTarget} onClick={apply}>{applying?"Applying…":`Apply ${studio} texture`}</button><small>{applyState}</small><button disabled={!image} onClick={png}>Export texture PNG</button><dl><div><dt>Target</dt><dd>{activeTarget?.kind??"None"}</dd></div><div><dt>BEV</dt><dd>Live · click to focus</dd></div><div><dt>Hero</dt><dd>{scene?.hero_lock?"Locked":"Free"}</dd></div></dl></aside>
  </section></>}
 </main>
}
