"use client";
import {ChangeEvent,useCallback,useEffect,useRef,useState} from "react";
import CarPreview,{MeshData} from "./CarPreview";
import ProjectionEditor from "./ProjectionEditor";
export default function Home(){
 const atlas=useRef<HTMLCanvasElement>(null);const [image,setImage]=useState<HTMLImageElement|null>(null),[base,setBase]=useState<HTMLImageElement|null>(null),[mesh,setMesh]=useState<MeshData|null>(null),[fileName,setFileName]=useState("No image selected"),[revision,setRevision]=useState(0),[applyState,setApplyState]=useState("Bridge ready"),[applying,setApplying]=useState(false);
 useEffect(()=>{const n=new Image();n.onload=()=>setBase(n);n.src="/tesla-model3-bodywork.png";fetch("/tesla-model3-uv0.json").then(r=>r.json()).then(setMesh)},[]);const rendered=useCallback(()=>setRevision(v=>v+1),[]);
 function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const u=URL.createObjectURL(f),n=new Image();n.onload=()=>{setImage(n);URL.revokeObjectURL(u)};n.src=u;setFileName(f.name)}
 function png(){const a=document.createElement("a");a.download="tesla-model3-livery.png";a.href=atlas.current?.toDataURL("image/png")??"";a.click()}
 async function apply(){if(!atlas.current)return;setApplying(true);setApplyState("Uploading texture…");try{const blob=await new Promise<Blob>((ok,no)=>atlas.current!.toBlob(v=>v?ok(v):no(new Error("PNG encoding failed")),"image/png"));const r=await fetch("http://127.0.0.1:8765/apply",{method:"POST",headers:{"Content-Type":"image/png"},body:blob}),v=await r.json();if(!r.ok)throw new Error(v.error);setApplyState(`Applied to actor ${v.actor_id}`)}catch(e){setApplyState(e instanceof Error?e.message:"Apply failed")}finally{setApplying(false)}}
 return <main><header><div><span className="eyebrow">CARLA SAFETY AGENT</span><h1>Vehicle Surface Studio</h1></div><div className="status"><i/>Tesla local projection · LOD0 · {mesh?.triangleCount??"…"} triangles</div></header><section className="workspace"><aside className="controls"><div className="section"><label>Verified target</label><select><option>Tesla Model 3 · exterior slot 5</option></select></div><div className="section"><label className="upload">Upload image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><small>{fileName}</small></div><div className="note"><strong>Direct body placement</strong><p>Choose top, left or right. The editor and CARLA material use the same continuous local-space projection, independent of the car&apos;s fragmented production UVs.</p></div></aside><div className="visuals"><div className="stage surface-stage"><div className="stagebar"><span>TESLA BODY SURFACE</span><span>Drag image · wheel to scale</span></div><ProjectionEditor mesh={mesh} base={base} image={image} output={atlas} onRender={rendered}/><canvas className="atlas-output" ref={atlas} width="2048" height="2048"/></div><CarPreview mesh={mesh} atlas={atlas} revision={revision}/></div><aside className="export"><span className="eyebrow">LIVE OUTPUT</span><h2>Send to CARLA</h2><p>The packed top, left and right projections map through normalized vehicle coordinates, so a door decal stays spatially continuous in CARLA.</p><button className="primary" disabled={!image||applying} onClick={apply}>{applying?"Applying…":"Apply live livery"}</button><small>{applyState}</small><button disabled={!image} onClick={png}>Export projection PNG</button><dl><div><dt>Editor</dt><dd>Body projection</dd></div><div><dt>Output</dt><dd>Local atlas · 2048²</dd></div><div><dt>Preview</dt><dd>Live 3D</dd></div></dl></aside></section></main>
}
