"use client";
import {RefObject,useEffect,useRef,useState} from "react";
import {MeshData} from "./CarPreview";
type View="top"|"left"|"right"; type Mode="decal"|"tile"|"cover";
type Props={mesh:MeshData|null;base?:HTMLImageElement|null;image:HTMLImageElement|null;output:RefObject<HTMLCanvasElement|null>;onRender:()=>void;useSourceUV?:boolean;label?:string};
function normal(a:number[],b:number[],c:number[]){const u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]];return[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]]}
function affine(s:number[][],d:number[][]){const q=s[0][0]*(s[1][1]-s[2][1])+s[1][0]*(s[2][1]-s[0][1])+s[2][0]*(s[0][1]-s[1][1]);if(Math.abs(q)<1e-5)return null;const v=(axis:number)=>[(d[0][axis]*(s[1][1]-s[2][1])+d[1][axis]*(s[2][1]-s[0][1])+d[2][axis]*(s[0][1]-s[1][1]))/q,(d[0][axis]*(s[2][0]-s[1][0])+d[1][axis]*(s[0][0]-s[2][0])+d[2][axis]*(s[1][0]-s[0][0]))/q,(d[0][axis]*(s[1][0]*s[2][1]-s[2][0]*s[1][1])+d[1][axis]*(s[2][0]*s[0][1]-s[0][0]*s[2][1])+d[2][axis]*(s[0][0]*s[1][1]-s[1][0]*s[0][1]))/q];const x=v(0),y=v(1);return[x[0],y[0],x[1],y[1],x[2],y[2]] as const}
export default function ProjectionEditor({mesh,image,output,onRender,useSourceUV=false,label="Vehicle bodywork"}:Props){
 const visible=useRef<HTMLCanvasElement>(null),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);const [view,setView]=useState<View>("left"),[mode,setMode]=useState<Mode>("decal"),[x,setX]=useState(50),[y,setY]=useState(50),[scale,setScale]=useState(46),[rotation,setRotation]=useState(0);
 useEffect(()=>{const canvas=visible.current;if(!canvas)return;const zoom=(event:WheelEvent)=>{if(!image)return;event.preventDefault();event.stopPropagation();setScale(value=>Math.max(5,Math.min(120,value-event.deltaY*.05)))};canvas.addEventListener("wheel",zoom,{passive:false});return()=>canvas.removeEventListener("wheel",zoom)},[image]);
 useEffect(()=>{const display=visible.current,out=output.current;if(!display||!out||!mesh)return;const dc=display.getContext("2d")!,oc=out.getContext("2d")!,size=display.width,a=mesh.vertices,mins=[Infinity,Infinity,Infinity],maxs=[-Infinity,-Infinity,-Infinity];for(let i=0;i<a.length;i+=5)for(let k=0;k<3;k++){mins[k]=Math.min(mins[k],a[i+k]);maxs[k]=Math.max(maxs[k],a[i+k])}const nrm=(v:number,k:number)=>(v-mins[k])/(maxs[k]-mins[k]),axis=view==="top"?1:2,aspect=(maxs[0]-mins[0])/(maxs[axis]-mins[axis]),frame={w:size*.9,h:size*.9/aspect,x:size*.05,y:(size-size*.9/aspect)/2},project=(p:number[])=>[frame.x+nrm(p[0],0)*frame.w,frame.y+(1-nrm(p[axis],axis))*frame.h],eligible=(p:number[][])=>{const n=normal(p[0],p[1],p[2]),m=Math.hypot(...n)||1;if(view==="top")return Math.abs(n[2])/m>.35;const cy=(p[0][1]+p[1][1]+p[2][1])/3;return Math.abs(n[1])/m>.35&&(view==="left"?cy<0:cy>0)};
  dc.fillStyle="#080d16";dc.fillRect(0,0,size,size);const tris:number[][][]=[];dc.beginPath();for(let i=0;i<a.length;i+=15){const p=[[a[i],a[i+1],a[i+2]],[a[i+5],a[i+6],a[i+7]],[a[i+10],a[i+11],a[i+12]]];if(!eligible(p))continue;const s=p.map(project);tris.push(s);dc.moveTo(s[0][0],s[0][1]);dc.lineTo(s[1][0],s[1][1]);dc.lineTo(s[2][0],s[2][1]);dc.closePath()}dc.fillStyle="#dce5e9";dc.fill();const layer=document.createElement("canvas");layer.width=layer.height=size;const lc=layer.getContext("2d")!;if(image){const w=scale/100*frame.w,h=w*image.height/image.width;if(mode==="cover")lc.drawImage(image,frame.x,frame.y,frame.w,frame.h);else{lc.translate(frame.x+x/100*frame.w,frame.y+y/100*frame.h);lc.rotate(rotation*Math.PI/180);if(mode==="decal")lc.drawImage(image,-w/2,-h/2,w,h);else for(let py=-size*1.5;py<size*1.5;py+=Math.max(20,h))for(let px=-size*1.5;px<size*1.5;px+=Math.max(20,w))lc.drawImage(image,px,py,w,h)}}dc.save();dc.globalCompositeOperation="source-atop";dc.drawImage(layer,0,0);dc.restore();dc.beginPath();for(const s of tris){dc.moveTo(s[0][0],s[0][1]);dc.lineTo(s[1][0],s[1][1]);dc.lineTo(s[2][0],s[2][1]);dc.closePath()}dc.strokeStyle="#243743";dc.globalAlpha=.25;dc.stroke();dc.globalAlpha=1;dc.fillStyle="#8da1ad";dc.font="24px sans-serif";dc.fillText("REAR",frame.x,frame.y+frame.h+34);dc.fillText("FRONT",frame.x+frame.w-dc.measureText("FRONT").width,frame.y+frame.h+34);
  oc.clearRect(0,0,out.width,out.height);if(useSourceUV){oc.fillStyle="#b8c1c5";oc.fillRect(0,0,out.width,out.height);if(image)for(let i=0;i<a.length;i+=15){const p=[[a[i],a[i+1],a[i+2]],[a[i+5],a[i+6],a[i+7]],[a[i+10],a[i+11],a[i+12]]];if(!eligible(p))continue;const s=p.map(project),d=[[a[i+3]*out.width,(1-a[i+4])*out.height],[a[i+8]*out.width,(1-a[i+9])*out.height],[a[i+13]*out.width,(1-a[i+14])*out.height]],t=affine(s,d);if(!t)continue;oc.save();oc.beginPath();oc.moveTo(d[0][0],d[0][1]);oc.lineTo(d[1][0],d[1][1]);oc.lineTo(d[2][0],d[2][1]);oc.closePath();oc.clip();oc.setTransform(...t);oc.drawImage(layer,0,0);oc.restore()}}else if(image){const third=out.width/3,index=view==="top"?0:view==="left"?1:2;oc.drawImage(layer,frame.x,frame.y,frame.w,frame.h,index*third,0,third,out.height)}onRender()
 },[mesh,image,output,onRender,view,mode,x,y,scale,rotation,useSourceUV]);
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drag.current)return;const r=e.currentTarget.getBoundingClientRect();setX(Math.max(0,Math.min(100,drag.current.x+(e.clientX-drag.current.px)/r.width*100/.9)));setY(Math.max(0,Math.min(100,drag.current.y+(e.clientY-drag.current.py)/r.height*100)))}
 return <div className="projection"><div className="viewtabs">{(["top","left","right"] as View[]).map(v=><button className={view===v?"active":""} key={v} onClick={()=>setView(v)}>{v} view</button>)}</div><div className="texture-modes">{(["decal","tile","cover"] as Mode[]).map(v=><button className={mode===v?"active":""} key={v} onClick={()=>setMode(v)}>{v}</button>)}</div><canvas ref={visible} width="1024" height="1024" onPointerDown={e=>{if(!image)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={px:e.clientX,py:e.clientY,x,y}}} onPointerMove={move} onPointerUp={()=>drag.current=null}/><div className="projection-controls"><label>Scale <input type="range" min="5" max="120" value={scale} onChange={e=>setScale(+e.target.value)}/></label><label>Rotation <input type="range" min="-180" max="180" value={rotation} onChange={e=>setRotation(+e.target.value)}/></label></div><small>{label} · top/left/right projection is baked into the real bodywork UV.</small></div>
}
