"use client";
import { RefObject,useEffect,useRef,useState } from "react";
import { MeshData } from "./CarPreview";
type View="top"|"left"|"right";
type P={mesh:MeshData|null;base:HTMLImageElement|null;image:HTMLImageElement|null;output:RefObject<HTMLCanvasElement|null>;onRender:()=>void};
function cross(a:number[],b:number[],c:number[]){const u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]];return[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]]}
function affine(ctx:CanvasRenderingContext2D,s:number[][],d:number[][],image:CanvasImageSource){const den=s[0][0]*(s[1][1]-s[2][1])+s[1][0]*(s[2][1]-s[0][1])+s[2][0]*(s[0][1]-s[1][1]);if(Math.abs(den)<1e-5)return;const a=(d[0][0]*(s[1][1]-s[2][1])+d[1][0]*(s[2][1]-s[0][1])+d[2][0]*(s[0][1]-s[1][1]))/den,c=(d[0][0]*(s[2][0]-s[1][0])+d[1][0]*(s[0][0]-s[2][0])+d[2][0]*(s[1][0]-s[0][0]))/den,e=(d[0][0]*(s[1][0]*s[2][1]-s[2][0]*s[1][1])+d[1][0]*(s[2][0]*s[0][1]-s[0][0]*s[2][1])+d[2][0]*(s[0][0]*s[1][1]-s[1][0]*s[0][1]))/den;const b=(d[0][1]*(s[1][1]-s[2][1])+d[1][1]*(s[2][1]-s[0][1])+d[2][1]*(s[0][1]-s[1][1]))/den,dv=(d[0][1]*(s[2][0]-s[1][0])+d[1][1]*(s[0][0]-s[2][0])+d[2][1]*(s[1][0]-s[0][0]))/den,f=(d[0][1]*(s[1][0]*s[2][1]-s[2][0]*s[1][1])+d[1][1]*(s[2][0]*s[0][1]-s[0][0]*s[2][1])+d[2][1]*(s[0][0]*s[1][1]-s[1][0]*s[0][1]))/den;ctx.save();ctx.beginPath();ctx.moveTo(...d[0] as [number,number]);ctx.lineTo(...d[1] as [number,number]);ctx.lineTo(...d[2] as [number,number]);ctx.closePath();ctx.clip();ctx.setTransform(a,b,c,dv,e,f);ctx.drawImage(image,0,0);ctx.restore()}
export default function ProjectionEditor({mesh,base,image,output,onRender}:P){const visible=useRef<HTMLCanvasElement>(null),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null),[view,setView]=useState<View>("top"),[x,setX]=useState(50),[y,setY]=useState(50),[scale,setScale]=useState(46),[rotation,setRotation]=useState(0);
 useEffect(()=>{const display=visible.current,out=output.current;if(!display||!out||!mesh)return;const dc=display.getContext("2d")!,oc=out.getContext("2d")!,size=display.width,a=mesh.vertices,project=(p:number[])=>view==="top"?[.5+p[1]*.56,.5-p[0]*.48]:[.5+p[0]*.48,.58-p[2]*.82],eligible=(p:number[][])=>{const n=cross(p[0],p[1],p[2]),m=Math.hypot(...n)||1;if(view==="top")return Math.abs(n[2])/m>.22&&(p[0][2]+p[1][2]+p[2][2])/3>-.08;const cy=(p[0][1]+p[1][1]+p[2][1])/3;return Math.abs(n[1])/m>.22&&(view==="left"?cy<0:cy>0)};dc.clearRect(0,0,size,size);dc.fillStyle="#080d16";dc.fillRect(0,0,size,size);const triangles:{s:number[][];d:number[][]}[]=[];dc.beginPath();for(let i=0;i<a.length;i+=15){const p=[[a[i],a[i+1],a[i+2]],[a[i+5],a[i+6],a[i+7]],[a[i+10],a[i+11],a[i+12]]];if(!eligible(p))continue;const s=p.map(q=>project(q).map(v=>v*size)),d=[[a[i+3]*2048,a[i+4]*2048],[a[i+8]*2048,a[i+9]*2048],[a[i+13]*2048,a[i+14]*2048]];triangles.push({s,d});dc.moveTo(s[0][0],s[0][1]);dc.lineTo(s[1][0],s[1][1]);dc.lineTo(s[2][0],s[2][1]);dc.closePath()}dc.fillStyle="#dce5e9";dc.fill();const layer=document.createElement("canvas");layer.width=layer.height=size;const lc=layer.getContext("2d")!;if(image){const w=scale/100*size,h=w*image.height/image.width;lc.translate(x/100*size,y/100*size);lc.rotate(rotation*Math.PI/180);lc.drawImage(image,-w/2,-h/2,w,h)}dc.save();dc.globalCompositeOperation="source-atop";dc.drawImage(layer,0,0);dc.restore();dc.beginPath();for(const {s} of triangles){dc.moveTo(s[0][0],s[0][1]);dc.lineTo(s[1][0],s[1][1]);dc.lineTo(s[2][0],s[2][1]);dc.closePath()}dc.strokeStyle="#243743";dc.globalAlpha=.45;dc.stroke();oc.clearRect(0,0,2048,2048);if(base)oc.drawImage(base,0,0,2048,2048);if(image)for(const t of triangles)affine(oc,t.s,t.d,layer);onRender()},[mesh,base,image,output,onRender,view,x,y,scale,rotation]);
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drag.current)return;const r=e.currentTarget.getBoundingClientRect();setX(Math.max(0,Math.min(100,drag.current.x+(e.clientX-drag.current.px)/r.width*100)));setY(Math.max(0,Math.min(100,drag.current.y+(e.clientY-drag.current.py)/r.height*100)))}
 return <div className="projection"><div className="viewtabs">{(["top","left","right"] as View[]).map(v=><button className={view===v?"active":""} key={v} onClick={()=>setView(v)}>{v} view</button>)}</div><canvas ref={visible} width="1024" height="1024" onPointerDown={e=>{if(!image)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={px:e.clientX,py:e.clientY,x,y}}} onPointerMove={move} onPointerUp={()=>drag.current=null} onWheel={e=>{if(image){e.preventDefault();setScale(v=>Math.max(5,Math.min(120,v-e.deltaY*.05)))}}}/><div className="projection-controls"><label>Scale <input type="range" min="5" max="120" value={scale} onChange={e=>setScale(+e.target.value)}/></label><label>Rotation <input type="range" min="-180" max="180" value={rotation} onChange={e=>setRotation(+e.target.value)}/></label></div><small>Paint on a recognizable body view; triangles project it back to Tesla UV0.</small></div>}
