"use client";
import {useState} from "react";
const bridge="http://127.0.0.1:8765";
const examples=["Town04 大雨夜间，前车在18米处急刹，自车速度15 m/s","生成一条双向4车道S弯道路，前方35米掉落6根金属管，有20棵树和8栋建筑","Town04 路口行人横穿，自车速度12 m/s，有雾"];
export default function ScenarioGeneratorPage({onEvaluationStarted}:{onEvaluationStarted?:()=>void}){
 const [text,setText]=useState(examples[0]),[seed,setSeed]=useState(7),[result,setResult]=useState<Record<string,unknown>|null>(null),[status,setStatus]=useState("Describe a safety-critical interaction in Chinese or English."),[busy,setBusy]=useState(false);
 async function call(path:string){const evaluating=path.endsWith("evaluate"),running=path.endsWith("run");setBusy(true);setStatus(evaluating?"Compiling and launching native UniAD evaluation…":running?"Building and running scenario in CARLA…":"Compiling description…");try{const r=await fetch(`${bridge}/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:text,seed})}),v=await r.json();if(!r.ok)throw new Error(v.error);setResult(v);setStatus(evaluating?"Native closed-loop evaluation started.":running?"Scenario finished. Results are shown below.":"Structured scenario ready for review.");if(evaluating)onEvaluationStarted?.()}catch(e){setStatus(e instanceof Error?e.message:"Scenario request failed")}finally{setBusy(false)}}
 function download(){if(!result)return;const blob=new Blob([JSON.stringify(result.scenario??result,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`scenario-${seed}.json`;a.click();URL.revokeObjectURL(a.href)}
 return <section className="scenario-page"><div className="scenario-compose"><span className="eyebrow">NATURAL LANGUAGE → STRUCTURED SCENE</span><h2>Safety Scenario Generator</h2><p>Compile a description into the executable scenario contract before changing CARLA.</p><textarea value={text} onChange={e=>setText(e.target.value)} rows={7}/><div className="scenario-actions"><label>Seed <input type="number" value={seed} onChange={e=>setSeed(+e.target.value)}/></label><button disabled={busy||!text.trim()} onClick={()=>call("scenario/compile")}>Compile & preview</button><button disabled={busy||!text.trim()} onClick={()=>call("scenario/run")}>Build & run in CARLA</button><button className="primary" disabled={busy||!text.trim()} onClick={()=>call("scenario/evaluate")}>Test this scene with UniAD</button></div><small>{status}</small><div className="scenario-examples">{examples.map(v=><button key={v} onClick={()=>setText(v)}>{v}</button>)}</div></div><div className="scenario-json"><div className="stagebar"><span>STRUCTURED SCENARIO JSON</span><button disabled={!result} onClick={download}>Download JSON</button></div><pre>{result?JSON.stringify(result,null,2):"Compile a description to inspect its actors, environment, map, assets and safety oracle."}</pre></div></section>
}
