"use client";
import {RefObject,useEffect,useRef} from "react";

type Kind="vehicle"|"road"|"building"|"pedestrian";
export default function Surface3DPreview({atlas,revision,kind,label}:{atlas:RefObject<HTMLCanvasElement|null>;revision:number;kind:Kind;label:string}){
 const canvas=useRef<HTMLCanvasElement>(null),angle=useRef(-.55),drag=useRef<{x:number;a:number}|null>(null);
 useEffect(()=>{const c=canvas.current,source=atlas.current;if(!c||!source)return;const ctx=c.getContext("2d")!;const draw=()=>{const d=devicePixelRatio||1;c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.setTransform(d,0,0,d,0,0);const w=c.clientWidth,h=c.clientHeight;ctx.fillStyle="#09101a";ctx.fillRect(0,0,w,h);const pattern=ctx.createPattern(source,"repeat")!;ctx.save();ctx.translate(w/2,h*.55);ctx.rotate(angle.current*.08);if(kind==="road"){ctx.transform(1,0,-.7,.45,0,0);ctx.fillStyle=pattern;ctx.fillRect(-w*.42,-h*.36,w*.84,h*.72);ctx.strokeStyle="#d8dde5";ctx.setLineDash([18,16]);ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-h*.36);ctx.lineTo(0,h*.36);ctx.stroke()}else if(kind==="pedestrian"){ctx.fillStyle="#d7b39a";ctx.beginPath();ctx.arc(0,-h*.27,34,0,Math.PI*2);ctx.fill();ctx.fillStyle=pattern;ctx.beginPath();ctx.roundRect(-52,-h*.16,104,h*.42,30);ctx.fill();ctx.fillRect(-78,-h*.1,26,h*.28);ctx.fillRect(52,-h*.1,26,h*.28);ctx.fillRect(-42,h*.22,32,h*.25);ctx.fillRect(10,h*.22,32,h*.25)}else{const bw=Math.min(230,w*.5),bh=Math.min(250,h*.48),depth=70,skew=Math.sin(angle.current)*depth;ctx.fillStyle=pattern;ctx.fillRect(-bw/2,-bh/2,bw,bh);ctx.save();ctx.transform(1,-.28*Math.sign(skew||1),0,1,0,0);ctx.globalAlpha=.68;ctx.fillRect(skew>0?bw/2:-(bw/2+Math.abs(skew)),-bh/2,Math.abs(skew),bh);ctx.restore();ctx.strokeStyle="#9ba8b8";ctx.strokeRect(-bw/2,-bh/2,bw,bh)}ctx.restore();ctx.fillStyle="#8390a3";ctx.font="11px system-ui";ctx.fillText("Proxy geometry · texture placement preview",16,h-18)};draw();(c as HTMLCanvasElement&{redraw?:()=>void}).redraw=draw},[atlas,kind]);
 useEffect(()=>{(canvas.current as HTMLCanvasElement&{redraw?:()=>void})?.redraw?.()},[revision]);
 return <div className="preview surface-3d"><div className="previewbar"><b>3D SURFACE PREVIEW</b><span>Drag to rotate · {label}</span></div><canvas ref={canvas} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,a:angle.current}}} onPointerMove={e=>{if(!drag.current)return;angle.current=drag.current.a+(e.clientX-drag.current.x)*.012;(e.currentTarget as HTMLCanvasElement&{redraw?:()=>void}).redraw?.()}} onPointerUp={()=>drag.current=null}/></div>
}
