"use client";
import {PointerEvent,RefObject,useEffect,useRef,useState} from "react";

type Props={image:HTMLImageElement|null;output:RefObject<HTMLCanvasElement|null>;onRender:()=>void;label:string;note:string;baseColor:string};
export default function SurfaceTextureEditor({image,output,onRender,label,note,baseColor}:Props){
 const preview=useRef<HTMLCanvasElement>(null),drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
 const [mode,setMode]=useState<"decal"|"tile">("decal"),[scale,setScale]=useState(46),[rotation,setRotation]=useState(0),[offset,setOffset]=useState({x:0,y:0});
 useEffect(()=>{const visible=preview.current,out=output.current;if(!visible||!out)return;const render=(ctx:CanvasRenderingContext2D,size:number)=>{ctx.clearRect(0,0,size,size);ctx.fillStyle=baseColor;ctx.fillRect(0,0,size,size);if(!image)return;const factor=scale/100,iw=image.width*factor,ih=image.height*factor;ctx.save();ctx.translate(size/2+offset.x*size/512,size/2+offset.y*size/512);ctx.rotate(rotation*Math.PI/180);if(mode==="decal")ctx.drawImage(image,-iw/2,-ih/2,iw,ih);else{const tw=Math.max(24,iw),th=Math.max(24,ih);for(let y=-size*2;y<size*2;y+=th)for(let x=-size*2;x<size*2;x+=tw)ctx.drawImage(image,x,y,tw,th)}ctx.restore()};render(visible.getContext("2d")!,visible.width);render(out.getContext("2d")!,out.width);onRender()},[baseColor,image,mode,onRender,offset,output,rotation,scale]);
 function down(e:PointerEvent<HTMLCanvasElement>){e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y}}
 function move(e:PointerEvent<HTMLCanvasElement>){if(!drag.current)return;setOffset({x:drag.current.ox+e.clientX-drag.current.x,y:drag.current.oy+e.clientY-drag.current.y})}
 function up(){drag.current=null}
 return <div className="projection building-editor"><div className="viewtabs"><button className={mode==="decal"?"active":""} onClick={()=>setMode("decal")}>local decal</button><button className={mode==="tile"?"active":""} onClick={()=>setMode("tile")}>tile surface</button></div><canvas ref={preview} width="1024" height="1024" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onWheel={e=>{e.preventDefault();setScale(v=>Math.max(5,Math.min(300,v-e.deltaY*.08)))}}/><div className="projection-controls"><label>Scale <input type="range" min="5" max="300" value={scale} onChange={e=>setScale(+e.target.value)}/></label><label>Rotation <input type="range" min="-180" max="180" value={rotation} onChange={e=>setRotation(+e.target.value)}/></label><button onClick={()=>setOffset({x:0,y:0})}>Center image</button></div><small>{label} · drag to position · wheel to scale. {note}</small></div>
}
