"use client";
import {RefObject,useEffect,useRef,useState} from "react";
import {MeshData} from "./CarPreview";
type Mode="decal"|"tile"|"cover";
export default function UVAtlasEditor({mesh,image,output,onRender}:{mesh:MeshData|null;image:HTMLImageElement|null;output:RefObject<HTMLCanvasElement|null>;onRender:()=>void}){
 const view=useRef<HTMLCanvasElement>(null),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 const [mode,setMode]=useState<Mode>("decal"),[x,setX]=useState(50),[y,setY]=useState(50),[scale,setScale]=useState(28),[rotation,setRotation]=useState(0);
 useEffect(()=>{const canvas=view.current,out=output.current;if(!canvas||!out||!mesh)return;const c=canvas.getContext("2d")!,o=out.getContext("2d")!,size=canvas.width,raw=mesh.vertices;
  const mask=document.createElement("canvas");mask.width=mask.height=size;const m=mask.getContext("2d")!;m.fillStyle="#dbe6eb";m.beginPath();for(let i=0;i<raw.length;i+=15){m.moveTo(raw[i+3]*size,(1-raw[i+4])*size);m.lineTo(raw[i+8]*size,(1-raw[i+9])*size);m.lineTo(raw[i+13]*size,(1-raw[i+14])*size);m.closePath()}m.fill();
  const art=document.createElement("canvas");art.width=art.height=size;const a=art.getContext("2d")!;if(image){const w=size*scale/100,h=w*image.height/image.width;if(mode==="cover")a.drawImage(image,0,0,size,size);else{a.translate(x/100*size,y/100*size);a.rotate(rotation*Math.PI/180);if(mode==="decal")a.drawImage(image,-w/2,-h/2,w,h);else for(let py=-size*1.5;py<size*1.5;py+=Math.max(12,h))for(let px=-size*1.5;px<size*1.5;px+=Math.max(12,w))a.drawImage(image,px,py,w,h)}}
  c.fillStyle="#080d16";c.fillRect(0,0,size,size);c.drawImage(mask,0,0);c.save();c.globalCompositeOperation="source-atop";c.drawImage(art,0,0);c.restore();c.beginPath();for(let i=0;i<raw.length;i+=15){c.moveTo(raw[i+3]*size,(1-raw[i+4])*size);c.lineTo(raw[i+8]*size,(1-raw[i+9])*size);c.lineTo(raw[i+13]*size,(1-raw[i+14])*size);c.closePath()}c.strokeStyle="rgba(30,51,64,.3)";c.stroke();
  o.clearRect(0,0,out.width,out.height);o.drawImage(art,0,0,out.width,out.height);onRender()
 },[mesh,image,output,onRender,mode,x,y,scale,rotation]);
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drag.current)return;const r=e.currentTarget.getBoundingClientRect();setX(Math.max(0,Math.min(100,drag.current.x+(e.clientX-drag.current.px)/r.width*100)));setY(Math.max(0,Math.min(100,drag.current.y+(e.clientY-drag.current.py)/r.height*100)))}
 return <div className="projection"><div className="viewtabs"><button className="active">European HGV bodywork UV0</button></div><div className="texture-modes">{(["decal","tile","cover"] as Mode[]).map(v=><button className={mode===v?"active":""} key={v} onClick={()=>setMode(v)}>{v}</button>)}</div><canvas ref={view} width="1024" height="1024" onPointerDown={e=>{if(!image)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={px:e.clientX,py:e.clientY,x,y}}} onPointerMove={move} onPointerUp={()=>drag.current=null} onWheel={e=>{if(image){e.preventDefault();setScale(v=>Math.max(3,Math.min(120,v-e.deltaY*.05)))}}}/><div className="projection-controls"><label>Scale <input type="range" min="3" max="120" value={scale} onChange={e=>setScale(+e.target.value)}/></label><label>Rotation <input type="range" min="-180" max="180" value={rotation} onChange={e=>setRotation(+e.target.value)}/></label></div><small>True material-slot-1 UV islands. Drag, wheel, tile or cover; the 3D preview uses the same UV coordinates.</small></div>
}
